### ISSUE TITLE
ERROR: uninitialized constant Target::OpenSSL

### ISSUE THREAD

**Issue by ap0l0** [urbanadventurer/WhatWeb#193] opened 2016-11-11 15:17 UTC
Every time I try to test a website with SSL it returns this error:

http://united.com [301 Moved Permanently] Akamai-Global-Host, Country[UNITED STATES][US], HTTPServer[AkamaiGHost], IP[23.2.80.82], RedirectLocation[https://united.com/], Strict-Transport-Security[max-age=15768000; preload]
https://united.com/ ERROR: uninitialized constant Target::OpenSSL

**Comment by vladwelt** [comment] 2016-12-01 23:42
Try to update ruby to 2.3

**Comment by nliplace** [comment] 2017-01-19 12:45
not solved.

**Comment by urbanadventurer** [comment] 2017-11-22 12:48
I cannot reproduce this error with ruby versions 1.9.3-p484 or 2.2.3. 
What of ruby version are you using?

**Comment by bcoles** [comment] 2017-12-01 07:39
Can't reproduce with:
* ruby-1.9.3-p551
* ruby-2.3.0

**Comment by urbanadventurer** [comment] 2017-12-01 11:40
@vladwelt and @NitescuLucian is this solved for you now? If not, what environment do you have?

**Comment by urbanadventurer** [comment] 2017-12-01 21:03
I'm closing this

**Closed by urbanadventurer** 2017-12-01 21:03 UTC
Labels: Can't reproduce error

**Comment by fcremo** [comment] 2018-04-18 11:59
I had the same problem on Arch Linux, using the archive of version 0.4.9, `ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]`.
I worked around the problem by requiring openssl on the top of lib/target.rb as suggested on this stackoverflow thread [1].
I'm not familiar with ruby so let me know what info I can provide 

[1] https://stackoverflow.com/questions/16980229/uninitialized-constant-openssl-nameerror

**Comment by ilyaglow** [comment] 2018-05-17 09:43
Reproduced this with `ruby 2.5.1`. Downgraded to `ruby 2.3` and [it works](https://github.com/ilyaglow/dockerfiles/blob/master/whatweb/Dockerfile) just fine.
