### ISSUE TITLE
Error:URI must be ascii only

### ISSUE THREAD

**Issue by LinkWj** [urbanadventurer/WhatWeb#223] opened 2017-11-27 15:45 UTC
Ruby version: 2.3.3p222
User WhatWeb 0.4.8 is ok,but User 0.4.9 have error:

> /usr/lib/ruby/2.3.0/uri/generic.rb:1102:in `rescue in merge': URI must be ascii only "http://\xEF\xBB\xBFidhost.kz/" (URI::InvalidURIError)
>         from /usr/lib/ruby/2.3.0/uri/generic.rb:1099:in `merge'
>         from /usr/lib/ruby/2.3.0/uri/rfc3986_parser.rb:89:in `each'
>         from /usr/lib/ruby/2.3.0/uri/rfc3986_parser.rb:89:in `inject'
>         from /usr/lib/ruby/2.3.0/uri/rfc3986_parser.rb:89:in `join'
>         from /usr/lib/ruby/2.3.0/uri/common.rb:265:in `join'
>         from /root/links/WhatWeb/lib/target.rb:244:in `get_redirection_target'
>         from ./whatweb:997:in `block (3 levels) in <main>'
>         from ./whatweb:980:in `loop'
>         from ./whatweb:980:in `block (2 levels) in <main>'

**Comment by urbanadventurer** [comment] 2017-11-30 18:36
This is related to the IDN domain issue.

**Comment by bcoles** [comment] 2017-12-01 14:44
Duplicate of #102

**Closed by bcoles** 2017-12-01 14:44 UTC
Labels: BUG, Feature Request
